version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=nijin
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:
